services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage       # 🔧 Bind Mount für einfache Sicherung & Analyse
    restart: unless-stopped
  
  n8n:
    build:
      context: ./n8n
      dockerfile: n8n.Dockerfile
    image: custom-n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n          # 🔧 Bind Mount – Workflows, Credentials im Klartext
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_BASIC_AUTH_ACTIVE=false
    restart: unless-stopped
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper
    ports:
      - "9000:9000"
    volumes:
      - whisper_cache:/root/.cache          # 🧱 Named Volume – Modelle + Whisper-Cache
    environment:
      - ASR_ENGINE=whisperx
      - ASR_MODEL=medium
    env_file:
      - .env
    restart: unless-stopped
  tester:
    image: curlimages/curl:latest
    container_name: tester
    entrypoint: tail -f /dev/null
    networks:
      - default
    restart: unless-stopped
  rag-upload:
    build:
      context: ./RAG
      dockerfile: upload.Dockerfile
    container_name: rag-upload
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - EMBEDDING_URL=http://embedding:8000/embed
    volumes:
      - ./data/uploads:/app/uploads         # 🔧 optional: z. B. für Logs oder persistente Uploads
    depends_on:
      - embedding
      - qdrant
    restart: unless-stopped
  embedding:
    build:
      context: ./embed-service
      dockerfile: embed.Dockerfile
    container_name: embedding
    ports:
      - "8002:8000"
    restart: unless-stopped
  caddy:
    image: caddy:latest
    container_name: caddy
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/html
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend-nginx
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - rag-upload
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start --optimized
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  ollama-mistral:
    ports:
      - "11431:11434"
    volumes:
      - ollama_mistral:/root/.ollama
    restart: unless-stopped

  ollama-mixtral:
    ports:
      - "11432:11434"
    volumes:
      - ollama_mixtral:/root/.ollama
    restart: unless-stopped

  ollama-commandr:
    ports:
      - "11433:11434"
    volumes:
      - ollama_commandr:/root/.ollama
    restart: unless-stopped

  ollama-yib:
    ports:
      - "11434:11434"
    volumes:
      - ollama_yib:/root/.ollama
    restart: unless-stopped

  ollama-hermes:
    ports:
      - "11435:11434"
    volumes:
      - ollama_hermes:/root/.ollama
    restart: unless-stopped

  ollama-nous:
    ports:
      - "11436:11434"
    volumes:
      - ollama_nous:/root/.ollama
    restart: unless-stopped

volumes:
  whisper_cache:
  caddy_data:
  caddy_config:
  keycloak_data:
  ollama_mistral:
  ollama_mixtral:
  ollama_commandr:
  ollama_yib:
  ollama_hermes:
  ollama_nous: